sudo: required

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
      - mystikweb:PXFBzS4uEnTzScjI1IlvmBcd#orleansdemo

jobs:
  include:
      - stage: build
        mono: none
        dotnet: 2.1.403
        language: csharp
        before_script:
          - chmod a+x ./build-silo.sh
        script:
          - ./build-silo.sh
      - stage: push
        services:
          - docker
        before_script:
          - chmod a+x ./push-silo.sh
        script: ./push-silo.sh