sudo: required

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
      - mystikweb:PXFBzS4uEnTzScjI1IlvmBcd#orleansdemo

jobs:
  include:
      - stage: build
        mono: none
        dotnet: 2.1.403
        language: csharp
        before_script:
          - chmod a+x ./build-solution.sh
        script: ./build-solution.sh
      - stage: buildSiloImage
        services:
          - docker
        before_script:
          - chmod a+x ./build-push-silo.sh
        script: ./build-push-silo.sh
      - stage: buildConfigurationImage
        services:
          - docker
        before_script:
          - chmod a+x ./buil-push-configuration.sh
        script: ./build-push-configuration.sh
      - stage: buildRuntimeImage
        services:
          - docker
        before_script:
          - chmod a+x ./build-push-runtime.sh
        script: ./build-push-runtime.sh