sudo: required

branches:
  only:
    - master
    - develop

mono: none
dotnet: 2.1.403
language: csharp

services:
    - docker

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
      - mystikweb:PXFBzS4uEnTzScjI1IlvmBcd#orleansdemo

jobs:
  include:
      - stage: build
        before_script:
          - chmod a+x ./build-silo.sh
        script:
          - ./build-silo.sh
      - stage: push
        before_script:
          -chmod a+x ./push-silo.sh
        script: ./push-silo.sh