CREATE TABLE [Runtime].[Reading]
(
	[Id] INT NOT NULL IDENTITY, 
	[Device] NVARCHAR(50) NOT NULL,
    [Type] NVARCHAR(50) NOT NULL, 
    [UOM] NVARCHAR(10) NOT NULL, 
	[DataType] NVARCHAR(50) NOT NULL,
    [Value] NCHAR(10) NOT NULL, 
    [InsertedAt] DATETIME2 NOT NULL, 
    CONSTRAINT [PK_Reading] PRIMARY KEY ([Id]) 
)
