CREATE TABLE [Runtime].[Reading]
(
	[Id] INT NOT NULL, 
	[Device] NVARCHAR(50) NOT NULL,
    [Type] NVARCHAR(50) NOT NULL, 
    [UOM] NVARCHAR(10) NOT NULL, 
	[DataType] NVARCHAR(50) NOT NULL,
    [Value] NCHAR(10) NOT NULL, 
	CONSTRAINT [PK_Runtime_Reading] PRIMARY KEY NONCLUSTERED HASH ([Id]) WITH (BUCKET_COUNT = 131072)
) WITH (MEMORY_OPTIMIZED = ON)
GO

ALTER DATABASE [$(DatabaseName)]
	ADD FILEGROUP [Runtime_Reading_FG] CONTAINS MEMORY_OPTIMIZED_DATA
