USE [master]
GO

ALTER DATABASE [DemoCluster] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE [DemoCluster]
GO

DROP LOGIN [ClusterManager]
GO

ALTER DATABASE [DemoConfiguration] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE [DemoConfiguration]
GO

DROP LOGIN [ConfigManager]
GO