USE [master]
GO

ALTER DATABASE [DemoCluster] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE [DemoCluster]
GO

DROP LOGIN [ClusterManager]
GO

ALTER DATABASE [DemoRuntime] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE [DemoRuntime]
GO

DROP LOGIN [RuntimeManager]
GO